using System.Collections;

public enum SpriteLayer {
	BackworldBackground,
    BackworldBackgroundObjects,
    BackworldEffects,
    BackworldPlatforms,
    ForeworldOutlines,
    ScoutBackworldRightFoot,
    ScoutBackworldRightHand,
    ScoutBackworldBody,
    ScoutBackworldSash,
    ScoutBackworldNeckerchief,
    ScoutBackworldHat,
    ScoutBackworldLeftHand,
    ScoutBackworldNeckerchiefTassleTwo,
    ScoutBackworldLeftFoot,
    ScoutBackworldNeckerchiefTassle,
    ScoutBackworldNeckerchiefTassleKnot,
    Curtain,
    ForeworldBackground,
    ForeworldBackgroundObjects,
    ForeworldEffects,
    ForeworldPlatforms,
    BackworldOutlines,
    ScoutForeworldRightFoot,
	ScoutForeworldRightHand,
	ScoutForeworldBody,
	ScoutForeworldSash,
	ScoutForeworldHat,
	ScoutForeworldNeckerchief,
	ScoutForeworldLeftHand,
	ScoutForeworldNeckerchiefTassleTwo,
    ScoutForeworldLeftFoot,
    ScoutForeworldNeckerchiefTassle,
    ScoutForeworldNeckerchiefTassleKnot
}
